# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-ci" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "a9c9d35d9eb10a35370b69d6a8faca2115226427cd3dcb554bd6996b53f45263"
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_amd64.zip"
    end
    on_arm do
      sha256 "be248cff1f145fd18548ca8aef039c410be501bfe520dd997eb1c1f838b3a0a2"
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "a09ed3b3d8b0aad012822fce6a13a3af84d1c1668decbb6a646a52e6cb3af5c0"
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_amd64.zip"
    end
    on_arm do
      sha256 "c1bb68cfc76332f5e84478789a6e34e2eb25b7395ccd0f47cf834ac342f15974"
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_arm64.zip"
    end
  end

  name "local-ci"
  desc "Run Docker-based CI pipelines locally"
  homepage "https://github.com/MrPuls/local-ci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-ci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-ci"]
    end
  end

  # No zap stanza required

end
