# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-ci" do
  name "local-ci"
  desc "Run Docker-based CI pipelines locally"
  homepage "https://github.com/MrPuls/local-ci"
  version "0.0.22"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-ci"

  on_macos do
    on_intel do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_amd64.zip"
      sha256 "c373f1afe7a8b7838924d85e4a150652ab7827499e1d854a0fd2a922155df080"
    end
    on_arm do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_arm64.zip"
      sha256 "03e5e427d9ee975b11e4691f26e2e9c0b2e29c2fc80341b71662dd8fefe64492"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_amd64.zip"
      sha256 "f2517036eeea0550272500638c5a631164afc5d537e0f9d1428a5a40a4df30a7"
    end
    on_arm do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_arm64.zip"
      sha256 "54f38b312d29304b187a8458fd9291b7c915c4b3e4261f37810a10d2b6b59ba2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-ci"]
    end
  end

  # No zap stanza required
end
