# This file was generated by GoReleaser. DO NOT EDIT.
cask "local-ci" do
  name "local-ci"
  desc "Run Docker-based CI pipelines locally"
  homepage "https://github.com/MrPuls/local-ci"
  version "0.0.21"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local-ci"

  on_macos do
    on_intel do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_amd64.zip"
      sha256 "53a2ee35962cc2d7145485ee422a8fc8e16fa38b10022d0911144a03c4eec8d1"
    end
    on_arm do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_darwin_arm64.zip"
      sha256 "e060bed3005440b42ae6022bbc5545158dba0c4cd5fbd36e93ea4e0827a26ea8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_amd64.zip"
      sha256 "50dc1d5da9c428ec82fc91dcb0f8470bd2386211e1be8c2af17e452dd049c2d1"
    end
    on_arm do
      url "https://github.com/MrPuls/local-ci/releases/download/v#{version}/local-ci_linux_arm64.zip"
      sha256 "438f03c3c9fde8f7868bc694f098006b6d4f25d9e9bffae1c88fbf42c900394a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-ci"]
    end
  end

  # No zap stanza required
end
